# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da0a106f255ee64e763f9801dbe8643ccdca4ae265bd479aa6c7a650a0a28a85c4c3399dab6435f963318704f4aaefa8ff7bdccba08f7df0530e0c9161cc188c

test:
  secret_key_base: 80d2d67b3cb4724d56a4a03097393294f50ebe899d0a8a381401d4b7be0d5c492ab2697b6e74122b48645c551141cf056f59214e830de14fd8a84ea519e1110b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
